# Generated by Django 5.0.2 on 2024-02-08 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DABubble', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_name',
            new_name='name',
        ),
    ]
