# Generated by Django 5.0.2 on 2024-02-15 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DABubble', '0003_chat_channel_message_chat_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DABubble.chat'),
        ),
    ]
