# Generated by Django 5.0.2 on 2024-02-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DABubble', '0006_alter_channel_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
