# Generated by Django 5.0.2 on 2024-02-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DABubble', '0007_channel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
