# Generated by Django 5.0.2 on 2024-02-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DABubble', '0009_customuser_chats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chat_id',
        ),
        migrations.AlterField(
            model_name='chat',
            name='messages',
            field=models.ManyToManyField(blank=True, null=True, related_name='chats', to='DABubble.message'),
        ),
    ]
