# Generated by Django 5.0.2 on 2024-02-19 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DABubble', '0010_remove_chat_chat_id_alter_chat_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='channel',
            name='chat',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='DABubble.chat'),
        ),
    ]
