# Generated by Django 5.0.2 on 2024-02-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DABubble', '0011_message_message_alter_channel_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='channel_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
