# Generated by Django 5.0.2 on 2024-02-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DABubble', '0013_remove_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
