# Generated by Django 5.0.2 on 2024-02-19 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DABubble', '0014_channel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='channel_id',
        ),
    ]
