# Generated by Django 5.0.2 on 2024-02-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DABubble', '0015_remove_chat_channel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='messages',
        ),
        migrations.AddField(
            model_name='chat',
            name='channel_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
