# Generated by Django 5.0.2 on 2024-02-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DABubble', '0018_alter_chat_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chat_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
