# Generated by Django 5.0.2 on 2024-02-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DABubble', '0019_message_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chat_id',
            field=models.IntegerField(default=0),
        ),
    ]
